spring.config.import=optional:classpath:application-secret.properties
server.port=5000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-post-size=10485760

# AWS CONFIG
aws.region=ap-south-1
aws.s3.bucket=my-secure-storage-files-2026
aws.dynamodb.table=Users

#environment variables:
    #Replace with your own master key for encryption/decryption
    #app.master-key=
    #AWS CREDENTIALS (Replace with your credentials)
    #cloudvault.aws.key=
    #cloudvault.aws.secret=


# COGNITO CONFIG (Replace with your IDs)
# Format: https://cognito-idp.{region}.amazonaws.com/{Pool-ID}
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_0cuYR2M9I
aws.cognito.userPoolId=ap-south-1_0cuYR2M9I
